### ISSUE TITLE
[HELP] Background image on all pages

### ISSUE THREAD

**Issue by mprandot** [barryvdh/laravel-snappy#332]
Hello guys!

I'm trying to put a watermark on my PDF, but it's working only on the first page.

Code:
```css
html {
    width: 21cm !important;
    height: 100% !important;
}
        
body {
   width: 21cm !important;
  height: 100% !important;
  background: url("{{ public_path('imagens/marcadagua.jpg') }}") no-repeat;
  -webkit-background-size: cover;
   -o-background-size: cover;
    -moz-background-size: cover;
     background-size: cover;
     padding: 15px 15px 15px 25px;
}

```
Someone can help me? It's a bug or i need to do something more?

**Comment by JoshuaMarviq** [comment]
```css
.bg-wrapper {
    position: fixed;
    width: 100%;
    height: 100%;
}
.bg-wrapper table {
    width: 100%;
    height: 100%;
}
.bg-wrapper table thead {
    display: table-header-group;
    background-image: url(...);
}
```

Make sure to leave out the <DOCTYPE>-line on top of your file. This will prevent Snappy from rendering `position: fixed`.

This worked, however, because I had a logo on top of the image, my content on page 2 would just go over the image. I wasn't able to add a top margin to every separate page.
So if anyone got a fix for that, I'd be glad to hear from them!
